name: 'variants-switch'
description: 'Switch to a custom variant of your deployment flavours. This requires Variants (https://github.com/Backbase/variants)'
author: 'Backbase B.V. <oss@backbase.com>'
branding:
  icon: "code"
  color: "blue"
  
inputs:
  spec:
    description: 'Specify the path to a Variants YAML configuration spec. Default is "variants.yml".'
    required: false
    default: 'variants.yml'
  platform:
    description: '"ios" or "android".'
    required: false
    default: 'default'
  variant:
    description: 'Variant you would like to switch to.'
    required: true
    default: 'default'
  version:
    description: "Variant's version."
    required: true
    default: 'latest'
  verbose:
    description: 'Log tech details for nerds.'
    required: true
    default: false

runs:
  using: "composite"
  steps:
    - name: Add PROJECT_PATH to GITHUB_ENV
      shell: bash
      run: |
        echo "project_path=$(pwd)" >> $GITHUB_ENV
          
    - name: Install variants
      shell: bash
      run: |
        if [[ "${{ inputs.version }}" == "latest" ]];
        then
          echo "Installing variants"
          brew install backbase/m/variants
          [[ "$?" == "1" ]] && echo "❌ Failed to install variants. Please ensure the version specified exists." 1>&2 && exit 1
        else
          if ! [[ "${{ inputs.version }}" =~ [[:digit:]]\.[[:digit:]]\.[[:digit:]] ]];
          then
            echo "❌ 'version' should match the pattern 'x.y.z'" 1>&2 && exit 1
          else
            brew tap backbase/m
            version_in_formula=`brew info backbase/m/variants | sed -n 's/.*\(stable [[:digit:]]\.[[:digit:]]\.[[:digit:]]\).*/\1/p' | cut -d ' ' -f2`
            if [[ "${{ inputs.version }}" > "$version_in_formula" ]] || [[ "${{ inputs.version }}" == "$version_in_formula" ]];
            then
              echo "Installing variants $version_in_formula from main formula"
              brew install backbase/m/variants
            else
              echo "Installing variants ${{ inputs.version }}"
              brew install "backbase/m/variants@${{ inputs.version }}"
            fi
            [[ "$?" == "1" ]] && echo "❌ Failed to install variants. Please ensure the version specified exists." 1>&2 && exit 1
          fi
        fi

    # - name: Variants Switch
    #   shell: bash
    #   if: ${{ env.INSTALLATION_STATUS == '0' }}
    #   run: |
    #     echo "Repository: ${{ github.repository }}"
    #     cd ${{ env.project_path }}
        
    #     if [[ ${{ inputs.platform }} == default ]];
    #     then
    #         if ${{ inputs.verbose }}
    #         then
    #             variants switch \
    #             --spec ${{ inputs.spec }} \
    #             --variant ${{ inputs.variant }} \
    #             --verbose
    #         else
    #             variants switch \
    #             --spec ${{ inputs.spec }} \
    #             --variant ${{ inputs.variant }}
    #         fi
    #     else
    #         if ${{ inputs.verbose }}
    #         then
    #             variants switch \
    #             --spec ${{ inputs.spec }} \
    #             --variant ${{ inputs.variant }} \
    #             --platform ${{ inputs.platform }} \
    #             --verbose
    #         else
    #             variants switch \
    #             --spec ${{ inputs.spec }} \
    #             --variant ${{ inputs.variant }} \
    #             --platform ${{ inputs.platform }}
    #         fi
    #     fi
