coverage:
  ignore:
    - Sources/VariantsCore/Commands/
  status:
    project:
      core:
        threshold: 5%
        paths:
          - Sources/VariantsCore
      tests:
        threshold: 5%
        paths:
          - Tests/VariantsCoreTests

    patch: no
