# Generated by Variants
MATCH_PARAMS = {
  MATCH_KEYCHAIN_NAME: ENV['MATCH_KEYCHAIN_NAME'],
  MATCH_KEYCHAIN_PASSWORD: ENV['MATCH_KEYCHAIN_PASSWORD'],
  
  # This is needed if your Match repository is private
  MATCH_GIT_BASIC_AUTHORIZATION: ENV['MATCH_GIT_BASIC_AUTHORIZATION'],
  
  # Match repository password, used to decrypt files
  MATCH_PASSWORD: ENV['MATCH_PASSWORD'],
  
  # Signing properties coming from Variants YAML spec. Do not change manually
  TEAMNAME: "Backbase B.V.",
  TEAMID: "R22WT7DX79",
  EXPORTMETHOD: "appstore",
  MATCHURL: "git@github.com:sample/match.git",
}.freeze