source 'https://rubygems.org'

gem 'cocoapods'
gem 'cocoapods-art'
gem 'fastlane'
gem 'slather'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
