source 'https://rubygems.org'
​
gem 'cocoapods', '~> 1.16"'
gem 'cocoapods-art'
gem 'fastlane'
gem 'slather'
gem 'nokogiri', '1.13.5'
​
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
