# frozen_string_literal: true

require File.expand_path('parameters/project_params.rb', __dir__)
require File.expand_path('parameters/match_params.rb', __dir__)

import('release/Fastfile')
import('Cohesion')
import('Cocoapods')
import('CLIDependencies')
import('SwiftLint')

# --- Before all, prepare

before_all do |lane, options|
    # - Install dependencies if needed
    # - Setup CI machine
    # - Install/update Cocoapods
    prepare
    
    # - Creates temporary keychain used by :match_signing_config
    # see 'fastlane/Match' file
    create_temporary_keychain
end

# --- After all, clean up

after_all do |lane, options|
    # - Removes temporary keychain used by :match_signing_config
    # see 'fastlane/Match' file
    remove_keychain
end

# --- Preparation phase

desc 'prepares the environment'
private_lane :prepare do |options|
  defaults = {
    derived_data_path: derived_data_path
  }.freeze
  options = defaults.merge(options)

  # Check if CLI dependencies are installed
  # Otherwise, install them
  prepare_dependencies
  
  # Temporarily disable update_fastlane due to
  # https://github.com/fastlane/fastlane/issues/16127
  # update_fastlane
  
  # Setup CI machine
  setup_jenkins(options)
  
  # Update/Install Pods
  pods_update
end

# --- Sonar checks

desc 'Run a sonar scan using the configuration in sonar-project.properties'
lane :sonar_report do |options|
  branch_name = options[:branch_name] || ''
  options.delete :branch

  defaults = {
    project_name: "ragnarok-ios #{branch_name}".strip,
    project_key: "ragnarok-ios:#{branch_name}".strip,
    project_version: get_version_number(target: app_scheme)
  }.freeze

  sonar(defaults.merge(options))
end

lane :coverage do |options|
  defaults = {
    scheme: app_scheme,
    cobertura_xml: true,
    input_format: "profdata",
    build_directory: derived_data_path,
  }.freeze

  slather(defaults.merge(options))
end

desc 'Run a lizard scan on the project'
lane :lizard_report do |options|
  defaults = {
    source_folder: 'Source',
    language: 'swift',
    export_type: 'xml',
    report_file: "#{reports_folder}/lizard-report.xml",
    executable: '/Users/jenkins/Library/Python/2.7/bin/lizard'
  }.freeze

  lizard(defaults.merge(options))
end

# --- Tests

desc 'Run all tests'
lane :tests do |options|
  defaults = {
    workspace: workspace,
    scheme: app_scheme,
    code_coverage: true,
    devices: test_devices,
    derived_data_path: derived_data_path,
    output_directory: reports_folder
  }.freeze

  scan(defaults.merge(options))
end

# --- Tagging

lane :update_tag do
  add_git_tag(
    tag: "build-#{get_build_number}"
  )
end

lane :commit_build_and_tag do
  git_commit(
    path: '.',
    message: "Bump build number to #{get_build_number}"
  )
  push_git_tags
end

# --- UI-Tests

desc 'Run UI Tests'
    lane :ui_test do |options|
    defaults = {
    workspace: workspace,
    scheme: uitest_scheme,
    output_directory: ui_test_reports_folder,
    destination: ui_test_destination,
    testplan: ui_test_plan,
    clean: true,
    max_concurrent_simulators: 1,
    disable_concurrent_testing: true,
    result_bundle: true,
    fail_build: false,
    slack_url: "https://hooks.slack.com/services/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",
    slack_channel: "#ui-tests",
    slack_message: "Advanzia iOS UI tests complete.\nDevice: #{ENV["DEVICE"]}, iOS #{ENV["OS"]}.\nLink: https://github.com/backbase-alm-advanzia/advanzia-mobile-ios/actions/runs/#{ENV["GITHUB_RUN_ID"]}"
    }.freeze

    scan(defaults.merge(options))
    xchtmlreport(result_bundle_path: "#{ui_test_reports_folder}/#{uitest_scheme}.xcresult")
end


workspace = PROJECT_PARAMS[:workspace]
app_scheme = PROJECT_PARAMS[:app_scheme]
derived_data_path = PROJECT_PARAMS[:derived_data_path]
reports_folder = PROJECT_PARAMS[:reports_folder]
swiftlint_path = PROJECT_PARAMS[:swiftlint_path]
test_devices = PROJECT_PARAMS[:test_devices]
build_number = ENV["JENKINS_BUILD_NUMBER"]
jenkins_job = ENV["JENKINS_JOB_URL"]
uitest_scheme = PROJECT_PARAMS[:uitest_scheme]
ui_test_destination = PROJECT_PARAMS[:ui_test_destination]
ui_test_reports_folder = PROJECT_PARAMS[:ui_test_reports_folder]
ui_test_plan = PROJECT_PARAMS[:ui_test_plan]
