APPCENTER_PARAMS = {
    APPCENTER_OWNER_NAME: ENV["APPCENTER_OWNER_NAME"],
    APPCENTER_API_TOKEN: ENV["APPCENTER_API_TOKEN"],
    APPCENTER_DESTINATION_GROUP: ENV["APPCENTER_DESTINATION_GROUP"]
}.freeze
