platform :ios, '14.0'

target 'VariantsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VariantsSample

  target 'VariantsSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VariantsSampleUITests' do
    # Pods for testing
  end

end
