# Generated by Variants

MATCH_PARAMS = {
  MATCH_KEYCHAIN_NAME: ENV['MATCH_KEYCHAIN_NAME'],
  MATCH_KEYCHAIN_PASSWORD: ENV['MATCH_KEYCHAIN_PASSWORD'],
  
  # This is needed if your Match repository is private
  MATCH_GIT_BASIC_AUTHORIZATION: ENV['MATCH_GIT_BASIC_AUTHORIZATION'],
  
  # Match repository password, used to decrypt files
  MATCH_PASSWORD: ENV['MATCH_PASSWORD'],
  
{% if parameterss %}
  # Signing properties coming from Variants YAML spec. Do not change manually
{% for param in parameters %}
  {{ param.name }}: "{{ param.value }}",
{% endfor %}
{% endif %}
}.freeze
