name: ci

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ develop ]
  push:
    branches: [ develop ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

jobs:
  tests:
    name: Test with Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        swift: ["5.10"]

    steps:
    - uses: actions/checkout@v2
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift }}

    - name: Make install
      run: make install
      
    - name: Tests
      run: make test

    #
    # CODECOV temporarily disabled due to issues running 'bundle install'
    # with racc-1.6.0 with native extensions.
    #
    # - uses: codecov/codecov-action@v1
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     file: ./test-reports/cobertura.xml
    #     fail_ci_if_error: true # optional (default = false)
    #     verbose: true # optional (default = false)
