name: CI

on:
  push:
    branches: [ develop ]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

jobs:
  build:
    name: Build with ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift: ["5.5"]
    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - uses: ruby/setup-ruby@v1

    - name: Test CLI Package
      run: swift test -v

    - name: Make install
      run: make install
      
    - name: Test VariantsCore
      if: matrix.os == 'macos-latest' # xcode available on macos only
      run: xcodebuild test -scheme VariantsCore

    - name: Bundle install
      run: bundle install
      
    - name: Code coverage report
      run: bundle exec slather coverage

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./test-reports/cobertura.xml
        fail_ci_if_error: false # optional (default = false)
        verbose: true # optional (default = false)
