name: CI

on:
  push:
    branches: [ develop ]
env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer

jobs:
  build:
    name: Build with Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
        swift: ["5.5"]
    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}

    - name: Bundle install
      run: |
        bundle install

    - name: Test CLI Package
      run: swift test -v

    - name: Make install
      run: make install

    - name: Test VariantsCore
      run: xcodebuild test -scheme VariantsCore

    - name: Code coverage report
      run: bundle exec slather coverage

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./test-reports/cobertura.xml
        fail_ci_if_error: false # optional (default = false)
        verbose: true # optional (default = false)
