name: "Danger Swift"

on:
  pull_request:
    types: [ opened, synchronize, edited ]

jobs:
  danger-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: danger/swift@bb4faf2c5613960b3de954c631cedd4dc63c3fef # v3.21.1
        with:
            args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}