name: SwiftLint

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install SwiftLint 0.47.1
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1 
        run: brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/6e249bca9f498d927d57748dacdc68241f81ce01/Formula/swiftlint.rb
      - name: Run SwiftLint
        run: swiftlint lint --strict --reporter github-actions-logging