name: SwiftLint

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        run: swiftlint lint --strict --reporter github-actions-logging